create table authors
(
    author_id int          not null
        primary key,
    aname     varchar(255) not null
);

INSERT INTO bookstoredb.authors (author_id, aname) VALUES (0, 'George, Jim');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (1, 'Stearn Robinson,Tom Corbett');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (2, 'Allen, David');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (3, 'Russel-Dugan-Stewart');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (4, 'Roe, Edward P.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (5, 'Barret, Richard Carter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (6, 'Dr.Seuss');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (7, 'Junior League of Houston');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (8, 'Kroger, William S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (9, 'John K. Wilson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (10, 'Morgenstern, Erin');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (11, 'Darke, Rick');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (12, 'Reginald Farrer');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (13, 'Morris, James (Jan)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (14, 'Fermor, Patrick Leigh');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (15, 'Cornwall, Judson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (16, 'PHILIP GEORGE');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (17, 'Gallagher, Fred & Rodney Caston');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (18, 'Pavy, F.W.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (19, 'Dan Sweeney');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (20, 'Finch, Simon');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (21, 'Clements, Samuel, Mark Twain, et al');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (22, 'Clifton-Taylor, Alec; Strong, Roy; Jordan, Robert Furneau...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (23, 'Kimmel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (24, 'Maher');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (25, 'H. V. Morton');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (26, 'Amanda Marrone');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (27, 'BARKER, Clive.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (28, 'HODGSON, William Hope.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (29, 'THOMPSON, Francis; KRISHNAMURTI, G; WILLIAMSON, Henry & O...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (30, 'Ratsch, Christian');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (31, 'THE LUTON NEWS.:');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (32, 'KELLY\'S DIRECTORIES .:');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (33, 'Blais, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (34, 'Margulis, Lynn; Gould, Stephen Jay; Schwartz, Karlene V.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (35, '(editor) Donald Lewis');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (36, '(editors) Gerald F. Hawthrone, etal.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (37, 'Colin Brown, ed.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (38, 'Agatha Christie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (39, 'Tredgold, Sir Robert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (40, 'No author');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (41, 'Dino Buzzati, translated by Stuart Hood');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (42, 'Mitchell, Eleanor Swann');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (43, 'SCHUBERT, Jochen [editor]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (44, 'COWLES, Frederick.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (45, 'Musin Ilia');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (46, 'SharovO. (ed.)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (47, 'Wilson, H. H.; Sharma, R. N.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (48, 'Shri Purohit Swami');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (49, 'John Andrews Arnett.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (50, 'Cooper, Artemis');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (51, 'Lang, George');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (52, 'Osman, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (53, 'John Bartholomew');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (54, 'A, Racinet');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (55, 'Markino, Yoshio');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (56, 'HURD, Rt Hon Lord Douglas, CH CBE');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (57, 'DOBBS, Michael');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (58, 'Oxenstierna, Eric');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (59, 'Kramer, Samuel Noah.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (60, 'Ingham, Bernard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (61, 'ART SPIEGELMAN');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (62, 'Neil Gaiman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (63, 'PRATCHETT Terry');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (64, 'STROUD, Jonathan');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (65, 'CANAVAN, Trudi');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (66, 'MICHAEL BARNES');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (67, 'Stanley Dance');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (68, 'Stanley Crouch');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (69, 'Dusan');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (70, 'D\' Harcourt, Raoul');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (71, 'John Mandeville; Lawrence G. Van Velzer and Peggy Gotthol...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (72, 'D\'Ambrosio, Joseph');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (73, 'Handforth, Thomas');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (74, 'Hall, Donald; Barbara Cooney, Illustrator');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (75, 'PARSONS, HENRY CHESTER');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (76, 'PAUL, ELLIOT, and KARL ZAMBONI');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (77, 'Forrestal, Dan J.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (78, 'Malcolm Torrie, Gladys Mitchell');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (79, 'Hardwick, M. Jeffrey');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (80, 'Williams, William Carlos');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (81, 'Milton, John');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (82, 'Nesbit, E. ; Bath, Hurbert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (83, 'Eric Carle');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (84, 'Bill Martin, John Archambault, (Illustrator) Lois Ehlert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (85, 'Ole Risom, (Illustrator) Richard Scarry');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (86, 'Gaskell, Elizabeth');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (87, 'Veeser, Harold [Editor]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (88, 'Fowles, John');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (89, 'Lee, Amy Freeman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (90, 'California State Mining Bureau');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (91, 'Andreas, A. T.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (92, 'Various');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (93, 'James Logan');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (94, 'A. E. Keys');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (95, 'Alan Moore; Kevin O\'Neill [Illustrator]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (96, 'Gaiman, Neil');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (97, 'Hawthorne, Julian');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (98, 'Scholl, Sophie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (99, 'Freud, Sigmund');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (100, '[Graetz, Hugo]; [Steinhardt, Jakob]; [Huth, Willy Robert]...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (101, 'Joseph Tomelleri');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (102, 'Siv Cedering; Robert Bly; William Stafford; Diane Wakoski...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (103, 'Petersen, Paulann');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (104, 'Young, Marguerite');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (105, 'Levertov, Denise & Jim Dine');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (106, 'Laura Hamje');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (107, 'Jessica Spring');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (108, 'G. Gordon Dewey [Editor] Vol. 1 No. 1');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (109, 'Bruce Arthur [Editor] Vol. 1 No. 5 April 1961');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (110, 'Harley R. MacCormack [Editor] Vol. 1 No. 2 February 1961');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (111, 'George Fox Jr. Vol. 2 No. 2 May 1957');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (112, 'Thollander, Earl (1922-2001)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (113, 'Colombier, Jeanne');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (114, 'Derek Cowan.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (115, 'Punch');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (116, 'Clare, Cassandra (signed)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (117, 'Dali, Salvador (illustrator); Lewis Carroll');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (118, 'Mitchell, Margaret');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (119, 'Doyle, Sir Arthur Conan');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (120, 'Dickens, Charles');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (121, 'Ono, Yoko');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (122, 'Child, Julia; Prud\'homme, Alex');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (123, 'KOHL, Cris');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (124, 'BOCKING, Richard C.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (125, 'ARMSTRONG, Frank');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (126, 'WATKINS-PITCHFORD, D. J.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (127, 'Valenzuela, Luisa');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (128, 'Garcia Marquez, Gabriel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (129, 'Faveron Patriau, Gustavo');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (130, 'Garcia Marquez, Gabrie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (131, 'Galeano, Eduardo');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (132, 'Gail Simone');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (133, 'Chris Claremont');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (134, 'Howard, Jean, and James Watters');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (135, 'Ford, Henry, II; Harold T. Youngren; and Others');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (136, 'Falconer. Thomas');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (137, 'Chambers. William and Robert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (138, 'Castro. C. Et al');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (139, 'PRATT, E. J.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (140, 'KINNELL, Galway');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (141, 'ATWOOD, Margaret');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (142, 'SOUSTER, Raymond');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (143, 'Chase, James Hadley. ( pseudonym of Rene Brabazon Raymond...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (144, 'Bruff, Nancy.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (145, 'Daley, Rosie; (Oprah Winfrey, Introduction)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (146, 'Deepak Chopra');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (147, 'King Jr, Martin Luther');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (148, 'Chernow, Ron');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (149, 'Kington, Donald M.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (150, 'Beveridge, Albert J.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (151, 'James B. Donovan (author); Erwin N. Griswold (foreword)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (152, 'Mark Strand');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (153, 'Henry Greenleaf Pearson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (154, 'Siegel, Bernie S. M.D.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (155, 'Pighini, Sue');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (156, 'Morton, H V');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (157, 'Becker, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (158, 'Goodhead, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (159, 'Harvie, Chris');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (160, 'Grier, David');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (161, 'mr JOHN REEVES');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (162, 'Ford, John M.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (163, 'Penelope Scambly Schott');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (164, 'Patrul Rinpoche');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (165, 'Illes, Judika');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (166, 'Flax, Brian D.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (167, 'Lovecraft, H P ( Howard Phillips ); Foreword By Frank Bel...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (168, 'Nigel Holmes, Paul Raven');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (169, 'Birkhead, Tim R.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (170, 'Watson, Jeff');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (171, 'Zimmerman, Dale A.; Pratt, Doug');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (172, 'Julian P. Hume & Michael Walters');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (173, 'Burke, James Lee');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (174, 'Burroughs, William S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (175, 'Grimm Brothers; (Retold and Illustrated by Robert Byrd)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (176, 'Say, Allen');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (177, 'Brown, Marcia');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (178, 'Kushner, Tony (Pictures by Maurice Sendak)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (179, 'LISA KLEYPAS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (180, 'FERN MICHAELS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (181, 'KATHLEEN E. WOODIWISS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (182, 'LISA KLEYPAS, KINLEY MACGREGOR, JULIA QUINN');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (183, 'Mastro, Jim');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (184, 'Biddlecombe, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (185, 'MAYLE, PETER');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (186, 'Mitchell G.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (187, 'Akunin Boris');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (188, 'Pulley Natasha');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (189, 'Shimada Soji');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (190, 'Nesbø Jo');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (191, 'Chogyam Trungpa');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (192, 'Daniel Goleman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (193, 'Lowenstein, Tom');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (194, 'J. C. Cleary');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (195, 'Danai Chanchaochai');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (196, 'Peter Scott');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (197, 'Sherwood, Mrs');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (198, 'Watts');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (199, 'Cameron, Mrs');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (200, 'Watts, Dr');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (201, 'Russo, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (202, 'McBride, James');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (203, 'Dirk Bogarde');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (204, 'Robert Galbrath');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (205, 'Ackroyd, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (206, 'Donald, Jon Lake, David');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (207, 'Kluxen, Kurt');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (208, 'Black, Peter R.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (209, 'Laqueur, Walter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (210, 'Sis, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (211, '(Edward Gorey) ELIOT, T. S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (212, 'VARGAS LLOSA, Mario.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (213, 'ISHIGURO, Kazuo.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (214, 'MORRISON, Toni.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (215, 'MILOSZ, Czeslaw.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (216, 'WALCOTT, Derek.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (217, 'Sakai, Stan');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (218, 'Masamune, Shiro');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (219, 'Hino, Matsuri (Author)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (220, 'Tomizawa, Hitoshi (Author, Artist)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (221, 'Kakifly');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (222, 'Fujisawa, Tohru (Author)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (223, 'Tolkien, J. R. R.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (224, 'Lindsay, Hilarie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (225, 'Kathleen Hale');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (226, 'Mary Norton');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (227, 'Andrew MacLean');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (228, 'Ron Marz,Tom Fowler');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (229, 'Peter Lenkov, Jeremy Barlow, Tony Parker');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (230, 'Gerard Way');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (231, 'Gerard Way, Gabriel Ba');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (232, 'WINTERS, JONATHAN');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (233, 'Multiple Contributors');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (234, 'Rice, Anne');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (235, 'Blatty, William Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (236, 'Sparks, Nicholas');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (237, 'Lyall, David [aka Annie S Swan]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (238, 'DANIELEWSKI, MARK Z.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (239, 'BRAM STOKER');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (240, 'Ketchum, Jack');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (241, 'King, Stephen');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (242, 'King, Stephen; Whelan, Michael [Illustrations]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (243, 'Gabaldon, Diana');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (244, 'Bittner, Rosanne');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (245, 'Rhodes, Jewell Parker');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (246, 'Thomas H. Raddall');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (247, 'PELTON, Sonya T.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (248, 'Dr. Seuss');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (249, 'Towles, Amor');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (250, 'BROWN, Pierce');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (251, 'Richard Matheson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (252, 'Powers, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (253, 'Michener, James A.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (254, 'SAWYER, Corinne Holt');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (255, 'DAVIES, Lindsey');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (256, 'DAVIS, Lindsey');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (257, 'Morrison, Toni');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (258, 'Bonnie Garmus');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (259, 'Doerr, Anthony');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (260, 'Cummins, Jeanine');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (261, 'Davis, Angela');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (262, 'Lawrence, Jacob [Art]; Peter T. Nesbett [Editor]; Michell...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (263, 'Anthony Doerr');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (264, 'Jeanine Cummins');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (265, 'Fitzgerald, F. Scott');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (266, 'Hughes, Langston');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (267, 'Celeste Ng');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (268, 'Emiliy St. John Mandel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (269, 'Grann, David');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (270, 'Wilkerson, Isabel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (271, 'Westover, Tara');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (272, 'Owens, Delia');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (273, 'Ng, Celeste');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (274, 'Meek, James B.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (275, '[Minnelli, Liza]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (276, 'Ackley, Edith Flack');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (277, 'Baird Bill');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (278, 'Tichenor, Tom');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (279, 'Crow, Nancy');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (280, 'Miller, Marie S.');
