create table authors
(
    author_id int          not null
        primary key,
    aname     varchar(255) not null
);

INSERT INTO bookstoredb.authors (author_id, aname) VALUES (0, 'George, Jim');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (1, 'Rudge, Bill');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (2, 'A. M. Krasner, Ph.D.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (3, 'Philip Gould');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (4, 'Dudley Pope');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (5, 'McCarthy, Ann');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (6, 'Rushdie, Salman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (7, 'Settle, Mary Lee');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (8, 'Stearn Robinson,Tom Corbett');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (9, 'Glassie, Henry');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (10, 'Thiselton-Dyer, T. F.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (11, 'Wilson, Edward S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (12, 'Valenzuela-Zapata, Ana G.; Nabhan, Gary Paul');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (13, 'Paul Doherty');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (14, 'Patrick Moore');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (15, 'Bresinsky, A.; Besl, H.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (16, 'Kroger, William S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (17, 'Junior League of Houston');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (18, 'Jacques Pepin');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (19, 'Blais, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (20, 'Madeleine Kamman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (21, 'Gilbertie, Sal');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (22, 'Frank, Lois Ellen');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (23, 'Somerville, Annie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (24, 'Portale, Alfred');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (25, 'Menghi, Umberto');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (26, 'Messinge, Sylvie [and] Gilles Plaisant, editors');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (27, 'Dino Buzzati, translated by Stuart Hood');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (28, 'William Dalrymple');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (29, 'Cornwall, Judson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (30, 'Darke, Rick');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (31, 'Alan Moore.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (32, 'Ed Hajim w/Glenn Plaskin');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (33, 'Hobbs, P[eter]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (34, 'Murakami, Maki');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (35, 'Kojo');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (36, 'Garvin, J.L. [Editor in Chief]; Hooper, Franklin H. [Amer...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (37, 'HOWARD WEINSTEIN');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (38, 'J. M. Dillard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (39, 'Kimmel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (40, 'Clifton-Taylor, Alec; Strong, Roy; Jordan, Robert Furneau...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (41, 'McCloskey, Robert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (42, 'Arrien, Angeles');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (43, 'Cayce, Edgar');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (44, 'Blavatsky, H.P.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (45, 'Regardie, Israel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (46, 'D.G. Hessayon');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (47, 'Agatha Christie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (48, 'Margulis, Lynn; Gould, Stephen Jay; Schwartz, Karlene V.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (49, 'Vogel, Steven');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (50, 'Wilson, H. H.; Sharma, R. N.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (51, 'Swami Rama');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (52, 'Hixon, Lex');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (53, 'Forrestal, Dan J.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (54, 'Country Living');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (55, 'Roberts, Paul');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (56, 'Wise, Murray R.; Brighton, Jack');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (57, 'Francix, Charles A. (Editor); Illinois Department Of Agri...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (58, 'Grant, Donald');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (59, 'Collings, Ellsworth; England, Alma Miller');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (60, 'Clive Cussler with Dirk Cussler');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (61, 'Crais, Robert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (62, 'Dobie, J. Frank');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (63, 'BELLOLI, Andrea P.A. (Editor): BRETTELL, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (64, 'Ceccuti, Cosimo; Cinelli, Carlo');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (65, 'ARTEMIEVA, Irina & GUDERZO, Mario');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (66, 'CANCEL, Luis, and others:');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (67, 'Handforth, Thomas');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (68, 'Hall, Donald; Barbara Cooney, Illustrator');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (69, 'Jane Yolen; John Schoenherr, Illustrator');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (70, 'HURD, Rt Hon Lord Douglas, CH CBE');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (71, 'Oxenstierna, Eric');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (72, 'Kramer, Samuel Noah.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (73, 'Musin Ilia');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (74, 'Gelfand Jakov');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (75, 'Korykhalova N.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (76, 'Zinoveva Larisa Aleksandrovna');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (77, 'Rocstro William Smith');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (78, 'Druskin Yakov');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (79, 'Protsjuk Daniil');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (80, 'Gaskell, Elizabeth');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (81, 'Veeser, Harold [Editor]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (82, 'Fowles, John');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (83, 'DeLillo, Don');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (84, 'Palmer, Parker J.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (85, 'MICHAEL BARNES');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (86, 'Stanley Dance');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (87, 'Stanley Crouch');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (88, 'PRATCHETT Terry');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (89, 'ART SPIEGELMAN');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (90, 'Neil Gaiman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (91, 'Kazu Kibuishi');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (92, 'Sakai, Stan');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (93, 'Masamune, Shiro');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (94, 'Hino, Matsuri (Author)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (95, 'Kakifly');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (96, 'Fujisawa, Tohru (Author)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (97, 'Chris Claremont');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (98, 'Gail Simone');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (99, 'Jeff Lemire, Brian Azzarello');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (100, 'Tolkien, J. R. R.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (101, 'Lindsay, Hilarie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (102, 'Kathleen Hale');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (103, 'Williams, William Carlos');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (104, 'Eric Carle');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (105, 'Bill Martin, John Archambault, (Illustrator) Lois Ehlert');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (106, 'Alan Moore; Kevin O\'Neill [Illustrator]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (107, 'Gaiman, Neil');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (108, 'O\'Brian, Patrick');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (109, 'Sis, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (110, 'Ward, Lynd');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (111, 'Hawthorne, Julian');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (112, 'Carter, Jimmy');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (113, 'Andrew MacLean');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (114, 'Peter Lenkov, Jeremy Barlow, Tony Parker');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (115, 'mr JOHN REEVES');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (116, 'Ford, John M.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (117, 'Penelope Scambly Schott');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (118, 'Burke, James Lee');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (119, 'Burroughs, William S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (120, 'King Jr, Martin Luther');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (121, 'Dirk Bogarde');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (122, 'Robert Galbrath');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (123, 'Mitchell G.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (124, 'Akunin Boris');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (125, 'Pulley Natasha');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (126, 'Shimada Soji');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (127, 'Marsons Angela');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (128, 'Sutanto Jesse');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (129, 'Lovecraft, H P ( Howard Phillips ); Foreword By Frank Bel...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (130, 'Lovecraft, H.P. ( Howard Phillips ); George T Wetzel; R A...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (131, 'Moore, Alan (signed) / Jacen Burrows (signed) William Chr...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (132, 'Birkhead, Tim R.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (133, 'Watson, Jeff');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (134, 'Nigel Holmes, Paul Raven');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (135, 'Brandwood, Geoff');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (136, 'Zimmerman, Dale A.; Pratt, Doug');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (137, 'Shores, Christopher; Etc.; Et Al');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (138, 'Summers, Dorothy');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (139, 'Child, Julia; Prud\'homme, Alex');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (140, 'White, Myrtle Rose');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (141, 'Bayley, John');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (142, 'Fraser, Dawn');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (143, 'Daley, Rosie; (Oprah Winfrey, Introduction)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (144, 'Deepak Chopra');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (145, 'Dougans, Inge; Suzanne Ellis, Suzanne Inge');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (146, 'Veronique Vienne; Erica Lennard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (147, 'John M.; William, Arkinstall (Charles Leslie, Foreword)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (148, 'FERN MICHAELS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (149, 'DIANA GABALDON');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (150, 'LISA KLEYPAS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (151, 'STEPHANIE LAURENS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (152, 'KATHLEEN E. WOODIWISS');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (153, 'Mark Strand');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (154, 'James B. Donovan (author); Erwin N. Griswold (foreword)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (155, 'Jorie Graham');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (156, 'Marianne Moore');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (157, 'Gary Snyder');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (158, 'Harold Bloom');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (159, 'Robert Penn Warren');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (160, 'Grimm Brothers; (Retold and Illustrated by Robert Byrd)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (161, 'Say, Allen');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (162, 'Brown, Marcia');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (163, 'Kushner, Tony (Pictures by Maurice Sendak)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (164, 'Van Allsburg, Chris');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (165, 'Base, Graeme');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (166, 'L\'Engle, Madeleine & Christine Davenier');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (167, 'Deedy, Carmen Agra');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (168, 'Garcia Marquez, Gabriel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (169, 'Valenzuela, Luisa');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (170, 'Garcia Marquez, Gabrie');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (171, 'Morton, H V');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (172, 'Becker, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (173, '(Edward Gorey) ELIOT, T. S.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (174, 'VARGAS LLOSA, Mario.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (175, 'ISHIGURO, Kazuo.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (176, 'MORRISON, Toni.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (177, 'MILOSZ, Czeslaw.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (178, 'WALCOTT, Derek.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (179, 'Chogyam Trungpa');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (180, 'J. C. Cleary');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (181, 'Danai Chanchaochai');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (182, 'Lowenstein, Tom');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (183, 'Daniel Goleman');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (184, 'Peter Scott');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (185, 'Easwaran, Eknath');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (186, 'Thomas Merton');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (187, 'Clare, Cassandra (signed)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (188, 'Vonnegut, Kurt (signed)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (189, 'Grafton, Sue (signed)');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (190, 'Russo, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (191, 'McBride, James');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (192, 'Flynn, Gillian');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (193, 'Gregory Maguire');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (194, 'Henry Greenleaf Pearson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (195, 'Siegel, Bernie S. M.D.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (196, 'Pighini, Sue');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (197, 'Shanon');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (198, 'Moore, Thomas');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (199, 'Mastro, Jim');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (200, 'Biddlecombe, Peter');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (201, 'MAYLE, PETER');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (202, 'Hellman, Renee');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (203, 'THACKERAY, WILLIAM MAKEPEACE');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (204, 'WINTERS, JONATHAN');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (205, 'Multiple Contributors');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (206, 'Rice, Anne');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (207, 'Koontz, Dean');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (208, 'Sparks, Nicholas');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (209, 'Lyall, David [aka Annie S Swan]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (210, 'Siddons, Anne Rivers');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (211, 'Chevalier, Tracy');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (212, 'Grann, David');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (213, 'Wilkerson, Isabel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (214, 'Westover, Tara');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (215, 'Towles, Amor');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (216, 'Owens, Delia');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (217, 'Ng, Celeste');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (218, 'Gabaldon, Diana');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (219, 'Bittner, Rosanne');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (220, 'Rhodes, Jewell Parker');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (221, 'Thomas H. Raddall');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (222, 'PELTON, Sonya T.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (223, 'SAWYER, Corinne Holt');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (224, 'DAVIES, Lindsey');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (225, 'DAVIS, Lindsey');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (226, 'EVANOVICH, Janet');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (227, 'Meek, James B.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (228, '[Minnelli, Liza]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (229, 'Baird Bill');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (230, 'Crow, Nancy');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (231, 'Tichenor, Tom');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (232, 'DANIELEWSKI, MARK Z.');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (233, 'BRAM STOKER');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (234, 'Ketchum, Jack');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (235, 'King, Stephen');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (236, 'King, Stephen; Whelan, Michael [Illustrations]');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (237, 'Morrison, Toni');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (238, 'Bonnie Garmus');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (239, 'Doerr, Anthony');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (240, 'Cummins, Jeanine');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (241, 'Davis, Angela');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (242, 'Lawrence, Jacob [Art]; Peter T. Nesbett [Editor]; Michell...');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (243, 'Hughes, Langston');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (244, 'Fitzgerald, F. Scott');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (245, 'Jeanine Cummins');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (246, 'Celeste Ng');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (247, 'Emiliy St. John Mandel');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (248, 'Dr. Seuss');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (249, 'Richard Matheson');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (250, 'BROWN, Pierce');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (251, 'Powers, Richard');
INSERT INTO bookstoredb.authors (author_id, aname) VALUES (252, 'Michener, James A.');
