create table books
(
    book_id     int          not null
        primary key,
    bname       varchar(255) not null,
    author_id   int          not null,
    pub_id      int          not null,
    category_id int          not null,
    price       varchar(255) not null,
    pub_year    int          not null,
    constraint books_ibfk_1
        foreign key (author_id) references authors (author_id)
            on update cascade on delete cascade,
    constraint books_ibfk_2
        foreign key (pub_id) references publishers (pub_id)
            on update cascade on delete cascade,
    constraint books_ibfk_3
        foreign key (category_id) references category (category_id)
            on update cascade on delete cascade
);

create index author_id
    on books (author_id);

create index category_id
    on books (category_id);

create index pub_id
    on books (pub_id);

INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (0, 'The Bare Bones Bible Handbook. 10 Minutes to Understanding Each Book of the Bible', 0, 0, 0, 'US$8.00 ', 2006);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (1, 'Dreamer\'s Dictionary', 1, 1, 1, 'US$6.00 ', 1986);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (2, 'Getting Things Done: The Art of Stress-Free Productivity', 2, 2, 2, 'US$12.00 ', 2001);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (3, 'Astronomy (2 Vol)', 3, 3, 3, 'US$30.00 ', 1926);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (4, 'MAY AND JUNE, A ROMANCE OF THE REVOLUTION', 4, 4, 4, 'US$15.00 ', 1888);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (5, 'Bennington Pottery and Porcelain - A Guide to Identification', 5, 5, 5, 'US$19.61 ', 1958);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (6, 'Horton Hears a Who', 6, 6, 6, 'US$700.00 ', 1954);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (7, 'Stop and Smell the Rosemary: Recipes and Traditions to Remember', 7, 7, 7, 'US$25.00 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (8, 'Clinical and Experimental Hypnosis: In Medicine, Dentistry and Psychology (signed)', 8, 8, 8, 'US$29.75 ', 1963);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (9, 'Budu or Twenty Years in Sarawak', 9, 9, 9, 'US$7.33 ', 1969);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (10, 'The Night Circus', 10, 10, 10, 'US$50.00 ', 2011);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (11, 'The American Woodland Garden: Capturing the Spirit of the Deciduous Forest', 11, 11, 11, 'US$52.30 ', 2002);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (12, 'The English Rock Garden Volumes 1 & 2 (two volumes)', 12, 11, 11, 'US$6.54 ', 1919);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (13, 'The Market Of Seleukia : Signed By The Author', 13, 12, 12, 'US$588.42 ', 1957);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (14, 'George Psychoundakis : A Letter To C.A.Trypanis (Limited Lettered Edition: Signed By The Author)', 14, 12, 12, 'US$385.74 ', 1999);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (15, 'DAVID WORSHIPED WITH A FERVENT FAITH', 15, 13, 13, 'US$6.47 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (16, 'DAILY GRACE FROM PHILLIPIANS AND COLOSSI', 16, 13, 13, 'US$4.58 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (17, 'Megatokyo, Vol. 1', 17, 14, 14, 'US$8.00 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (18, 'On Carbohydrate Metabolism', 18, 15, 15, 'US$65.38 ', 1906);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (19, 'Original Vintage Luggage Label - Grand Hotel des Wagons Lits, Peking', 19, 16, 16, 'US$183.07 ', 1930);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (20, 'Simon Finch Rare Books', 20, 17, 17, 'US$65.38 ', 1886);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (21, 'Mark Twain\'s Letters Volume I 1854 to 1866', 21, 18, 18, 'US$15.00 ', 1988);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (22, 'Spirit of the Age', 22, 19, 19, 'US$6.54 ', 1976);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (23, 'Financial Accounting: Tools for Business Decision Making', 23, 20, 20, 'US$20.99 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (24, 'Fundamentals Of Cost Accounting', 24, 20, 20, 'US$19.88 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (25, 'In Search of England / In Search of Ireland', 25, 21, 21, 'US$65.38 ', 1936);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (26, 'Uninvited', 26, 22, 22, 'US$1.13 ', 2007);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (27, 'THE DAMNATION GAME. Inscribed by the Author.', 27, 23, 23, 'US$45.00 ', 1986);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (28, 'OUT OF THE STORM. Uncollected Fantasies. One of 14 Special Copies Signed by the Editor.', 28, 23, 23, 'US$35.00 ', 1975);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (29, 'THE HOUND OF HEAVEN. A Commemorative Volume. Edited and Introduced by G. Krishnamurti. SIGNED BY ...', 29, 23, 23, 'US$200.00 ', 1967);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (30, 'Plants of Love. The History of Aphrodisiacs and a Guide to Their Identification and Use', 30, 24, 24, 'US$17.00 ', 1997);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (31, 'The Luton News\' Directory of Luton. (1936).', 31, 25, 25, 'US$39.23 ', 1936);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (32, 'Kelly\'s Directory Of Hull And Neighbourhood 1939 .', 32, 25, 25, 'US$39.23 ', 1939);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (33, 'Try This at Home', 33, 26, 26, 'US$29.00 ', 2013);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (34, 'Five Kingdoms: An Illustrated Guide to the Phyla of Life on Earth', 34, 27, 27, 'US$19.99 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (35, 'Dictionary Of Evangelical Biography, 1730-1860 (2 Volume Set)', 35, 28, 28, 'US$45.47 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (36, 'Dictionary of Paul and His Letters (The IVP Bible Dictionary Series)', 36, 28, 28, 'US$26.52 ', 1993);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (37, 'The New International Dictionary of New Testament Theology, Vol. 1-3', 37, 28, 28, 'US$18.95 ', 1981);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (38, 'The Murder of Roger Ackroyd; The Seven Dials Mystery; The Murder at the Vicarage; Peril at End Ho...', 38, 29, 29, 'US$65.38 ', 1955);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (39, 'The Mysterious Mr Quin; The Murder at the Vicarage; The Sittaford Mystery; Why Didn t They Ask Ev...', 38, 29, 29, 'US$52.30 ', 1944);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (40, 'Xhosa; Tales of Life from the African Veld', 39, 9, 30, 'US$9.42 ', 1973);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (41, 'History of Southern and Central Africa, The; It\'s Topography, Geography, Natural Productions, &c....', 40, 9, 30, 'US$3.14 ', 1111);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (42, 'The Tartar Steppe', 41, 30, 31, 'US$13.01 ', 1985);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (43, 'Postscript to Seven homes', 42, 4, 32, 'US$25.39 ', 1960);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (44, 'Heinrich Boll: Briefe Aus Dem Krieg 1939-1945 Bands 1 & 2', 43, 31, 33, 'US$21.00 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (45, 'NOT FAR FROM THE SMOKE. Inscribed by the Author.', 44, 23, 34, 'US$250.00 ', 1935);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (46, 'Jazyk dirizherskogo zhesta.', 45, 32, 35, 'US$16.27 ', 2007);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (47, 'Accordion and Bayan Performance. Method, theory and history', 46, 32, 35, 'US$9.04 ', 2006);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (48, 'The Vishnu Purana', 47, 33, 36, 'US$32.69 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (49, 'The Geeta', 48, 33, 36, 'US$17.00 ', 1935);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (50, 'Bibliopegia: Or, the Art of Bookbinding in All Its Branches; Illustrated with Engravings.', 49, 34, 37, 'US$150.00 ', 1835);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (51, 'Writing at the kitchen table: The authorized biography of Elizabeth David', 50, 35, 38, 'US$12.50 ', 1999);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (52, 'Nobody Knows the Truffles I\'ve Seen', 51, 35, 38, 'US$17.50 ', 1999);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (53, 'Books 1,2,3,4 All signed 1st Prints: The Thursday Murder Club, The Man Who Died Twice (Waterstone...', 52, 36, 39, 'US$1,000.00 ', 2020);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (54, 'The Citizen\'s Atlas of the World', 53, 37, 40, 'US$61.13 ', 1935);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (55, 'Le Costume Historique Tome Ii. Cinq Cents Planches Troiscents En Couleurs, Or Et Argent Deux Cent...', 54, 38, 41, 'US$1,000.00 ', 1879);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (56, 'Recollections And Reflections Of A Japanese Artist', 55, 38, 41, 'US$695.00 ', 1931);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (57, 'MEMOIRS', 56, 39, 42, 'US$26.15 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (58, 'THE EDGE OF MADNESS', 57, 39, 42, 'US$19.61 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (59, 'The World of the Norsemen', 58, 40, 43, 'US$13.63 ', 1967);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (60, 'The Sumerians: Their History, Culture, And Character.', 59, 40, 43, 'US$10.22 ', 1971);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (61, 'Kill the Messenger', 60, 41, 44, 'US$74.03 ', 1991);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (62, 'Maus a Survivors Tale : My Father Bleeds Histry', 61, 42, 45, 'US$9.98 ', 1986);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (63, 'The Sleeper and the Spindle', 62, 42, 45, 'US$9.98 ', 2015);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (64, 'The Fifth Elephant', 63, 43, 46, 'US$13.08 ', 1999);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (65, 'Jingo', 63, 43, 46, 'US$11.77 ', 1997);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (66, 'The Amulet of Samarkand', 64, 43, 46, 'US$11.12 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (67, 'Priestess of the White (Age of the Five Book One)', 65, 43, 46, 'US$9.15 ', 2006);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (68, 'GOLD IN ONTARIO (signed copy)', 66, 44, 47, 'US$30.00 ', 1995);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (69, 'The world of Earl Hines (The world of swing ; v. 2)', 67, 45, 48, 'US$55.00 ', 1977);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (70, 'Kansas City Lightning: The Rise and Times of Charlie Parker', 68, 45, 48, 'US$8.50 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (71, 'The New Magic-Fit Master Pattern', 69, 46, 49, 'US$23.00 ', 1984);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (72, 'Textiles of Ancient Peru and Their Techniques', 70, 46, 49, 'US$40.25 ', 1974);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (73, 'The Travels of Sir John Mandeville Beyond the Holy Land', 71, 47, 50, 'US$131.00 ', 2019);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (74, 'Emily and Oscar (SIGNED)', 72, 47, 50, 'US$315.00 ', 1979);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (75, 'MEI LI', 73, 48, 51, 'US$27.99 ', 1938);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (76, 'Ox-Cart Man', 74, 48, 51, 'US$49.99 ', 1979);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (77, 'Four letters, signed "H. C. Parsons," from railroad executive and one-time owner of Natural Bridg...', 75, 49, 52, 'US$300.00 ', 1890);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (78, 'How to be a returned soldier', 76, 49, 52, 'US$125.00 ', 1944);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (79, 'The Kernel and the Bean: The 75-Year Story of the Staley Company', 77, 50, 53, 'US$29.99 ', 1982);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (80, 'The ABC Murders', 38, 51, 29, 'US$1,111.47 ', 1936);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (81, 'Shades of Darkness Signed Gladys Mitchell, Malcolm Torrie', 78, 51, 29, 'US$1,111.47 ', 1970);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (82, 'Murder In the Mews', 38, 51, 29, 'US$2,288.32 ', 1937);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (83, 'Lord Edgware Dies', 38, 51, 29, 'US$65.38 ', 1933);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (84, 'Mall Maker Victor Gruen, Architect of an American Dream', 79, 52, 19, 'US$40.00 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (85, 'SOUR GRAPES: A Book of Poems', 80, 53, 54, 'US$50.00 ', 1921);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (86, 'PARADISE LOST. A POEM IN TWELVE BOOKS; [bound with] PARADISE REGAIN\'D: A POEM IN IV BOOKS; [and] ...', 81, 53, 54, 'US$500.00 ', 1691);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (87, 'A Little Girl\'s Song - Vintage Sheet Music', 82, 54, 55, 'US$19.99 ', 1908);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (88, 'The Very Hungry Caterpillar', 83, 55, 56, 'US$10.99 ', 1994);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (89, 'Chicka Chicka Boom Boom (Classic Board Books)', 84, 55, 56, 'US$5.95 ', 2012);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (90, 'I Am a Bunny', 85, 55, 56, 'US$9.99 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (91, 'North and South (Penguin Classics)', 86, 56, 57, 'US$25.00 ', 1970);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (92, 'The New Historicism', 87, 56, 57, 'US$50.00 ', 1989);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (93, 'The French Lieutenant\'s Woman (Signet)', 88, 56, 57, 'US$17.00 ', 1981);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (94, 'Hobby Horses', 89, 57, 58, 'US$275.00 ', 1940);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (95, 'Mineral Productions, County Maps and Mining Laws of California, Bulletin No. 56', 90, 58, 40, 'US$325.00 ', 1909);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (96, 'Illustrated Historical Atlas of the State of Minnesota', 91, 58, 40, 'US$1,150.00 ', 1874);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (97, 'The Annual Register or a View of the History, Politics and Literature for the Year 1758', 92, 59, 57, 'US$45.60 ', 1791);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (98, 'McIan\'s Costumes of the Clans of Scotland', 93, 59, 57, 'US$23.54 ', 1899);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (99, 'A History of Eastington, Near Stonehouse in Gloucestershire', 94, 59, 57, 'US$47.68 ', 1111);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (100, 'The League of Extraordinary Gentlemen, The Black Dossier, Absolute Edition', 95, 60, 59, 'US$12.97 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (101, 'The Sandman 1: Preludes & Nocturnes', 96, 60, 59, 'US$10.83 ', 2010);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (102, 'The History of the United States from 1492 to 1912 (Three Volume Set)', 97, 61, 60, 'US$35.00 ', 1912);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (103, 'Sophie Scholl\'s Signed Membership Suspension Request From the Bund Deutscher Mädel', 98, 62, 52, 'US$994.64 ', 1939);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (104, '[ALS.] Sigmund Freud\'s Autograph Letter in German to Frau Wolff', 99, 62, 52, 'US$994.64 ', 1927);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (105, 'Hugo Graetz\'s Guestbook with Original Artworks by Members of the Novembergruppe', 100, 62, 52, 'US$1,864.95 ', 1965);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (106, 'Rock Greenling', 101, 63, 61, 'US$950.00 ', 2019);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (107, 'Poetry/Art Broadside Series', 102, 63, 61, 'US$20.00 ', 1985);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (108, 'Lethe\'s Poppy [Broadside]', 103, 63, 61, 'US$25.00 ', 1989);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (109, 'Leaves, Leaves', 104, 63, 61, 'US$20.00 ', 1984);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (110, 'The Freeing of the Dust / Blue Egyptian Water Lily [Broadside / Print]', 105, 63, 61, 'US$20.00 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (111, '\'Fern Gully\' Limited Edition Signed Print', 106, 63, 61, 'US$40.00 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (112, 'SCATTERED EPHEMERA - Tacoma 2004', 107, 63, 61, 'US$30.00 ', 1994);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (113, 'Showcase Magazine Collector\'s Edition', 108, 64, 62, 'US$50.00 ', 1960);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (114, 'Gentleman Magazine', 109, 64, 62, 'US$25.00 ', 1961);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (115, 'Debonair Magazine', 110, 64, 62, 'US$25.00 ', 1960);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (116, 'Tiger Magazine', 111, 64, 62, 'US$25.00 ', 1957);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (117, 'Morton Salt Co. Grand Saline, TexasThe loading machine operator', 112, 65, 63, 'US$125.00 ', 1987);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (118, 'Bretagne 1939. Guide Duran. Edition Hachette.(Guides Touristiques)', 113, 65, 63, 'US$50.00 ', 1932);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (119, 'Cutthroat Trout. Signed limited edition.', 114, 65, 63, 'US$50.00 ', 1977);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (120, 'Punch, Volume CCXV, 7 July to 29 December 1948', 115, 59, 64, 'US$23.14 ', 1948);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (121, 'The Infernal Devices, Book Three, Clockwork Princess (signed, and with 10 Collector Postcards)', 116, 66, 65, 'US$300.00 ', 2013);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (122, 'Alice\'s Adventures in Wonderland (Signed limited edition)', 117, 67, 66, 'US$12,500.00 ', 1969);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (123, 'Gone with the Wind (Inscribed First Edition)', 118, 67, 66, 'US$2,950.00 ', 1936);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (124, 'The Works of Arthur Conan Doyle (Signed author\'s edition in 12 vols.)', 119, 67, 66, 'US$950.00 ', 1903);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (125, 'Works (Signed limited edition in 40 vols.)', 120, 67, 66, 'US$7,500.00 ', 1908);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (126, 'Grapefruit (Signed First Edition)', 121, 67, 66, 'US$19,500.00 ', 1971);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (127, 'My Life in France', 122, 68, 67, 'US$10.19 ', 2009);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (128, 'Shipwreck Tales: The St. Clair River (to 1900)', 123, 69, 68, 'US$35.00 ', 1987);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (129, 'Mighty River: A Portrait of the Fraser', 124, 69, 68, 'US$40.00 ', 1997);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (130, 'Rock, River & Thorn: The Big Bend of the Rio Grande', 125, 69, 68, 'US$50.00 ', 2001);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (131, 'A Summer on the Nene', 126, 69, 68, 'US$50.00 ', 1967);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (132, 'The Censors (A Bilingual Selection of Stories)', 127, 70, 69, 'US$10.00 ', 1988);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (133, 'Living to Tell the Tale', 128, 70, 69, 'US$7.50 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (134, 'Strange Pilgrims: Twelve Stories', 128, 70, 69, 'US$15.00 ', 1993);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (135, 'The Antiquarian', 129, 70, 69, 'US$7.50 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (136, 'Memories of My Melancholy Whores', 130, 70, 69, 'US$20.00 ', 2005);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (137, 'Memory of Fire, II: Faces and Masks, Part Two of a Trilogy', 131, 70, 69, 'US$10.00 ', 1985);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (138, 'The Movement Vol. 2: Fighting for the Future (The New 52)', 132, 71, 70, 'US$16.99 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (139, 'X-Treme X-Men, Vol. 1: Destiny (Xtreme)', 133, 71, 70, 'US$14.99 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (140, 'JEAN HOWARD\'S HOLLYWOOD: A PHOTO MEMOIR', 134, 53, 71, 'US$95.00 ', 1989);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (141, 'CHARLES H. NIEPOTH\'S ARCHIVE OF FORD MOTOR COMPANY MATERIAL (1947-1958)', 135, 53, 71, 'US$95.00 ', 1947);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (142, 'On Surnames and the Rules of Law Affecting Their Change, Second Edition.BOUND WITH Supplement to ...', 136, 72, 72, 'US$32.69 ', 1862);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (143, 'Chambers\'s Encyclopaedia. A Dictionary of Universal Knowledge. New Edition in Ten Volumes. NEAR F...', 137, 72, 72, 'US$385.74 ', 1906);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (144, 'México y Sus Alrededores. Coleccion De Vistas Trajes y Monumentos Por C. Castro,J. Campillo,L. Au...', 138, 72, 72, 'US$313.83 ', 1855);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (145, 'The Witches\' Brew', 139, 69, 73, 'US$25.00 ', 1925);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (146, 'The Book of Nightmares', 140, 69, 73, 'US$45.00 ', 1971);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (147, 'The Journals of Susanna Moodie: Poems by Margaret Atwood', 141, 69, 73, 'US$40.00 ', 1970);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (148, 'Collected Poems of Raymond Souster Volume Two 1955-62', 142, 69, 73, 'US$20.00 ', 1981);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (149, 'The Titanic', 139, 69, 73, 'US$25.00 ', 1935);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (150, 'TWELVE CHINKS AND A WOMAN. (Book #160 in the Vintage Harlequin Paperbacks Series; Later Published...', 143, 73, 74, 'US$21.00 ', 1952);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (151, 'THE MANATEE (Vintage HARLEQUIN Book #1; Strange Loves of a Sea Man; Nantucket at the height of th...', 144, 73, 74, 'US$49.00 ', 1949);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (152, 'The FLESH of the ORCHID. (# 111 in the Vintage Harlequin Series) story of Carol Blandish, daughte...', 143, 73, 74, 'US$89.00 ', 1951);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (153, 'IN THE KITCHEN WITH ROSIE: Oprah\'s Favorite Recipes', 145, 74, 75, 'US$12.50 ', 1994);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (154, 'POWER, FREEDOM AND GRACE : Living from the Source of Lasting Happiness', 146, 74, 75, 'US$16.50 ', 2006);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (155, 'Stride Toward Freedom: The Montgomery Story', 147, 75, 76, 'US$35.00 ', 1958);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (156, 'Alexander Hamilton', 148, 75, 76, 'US$12.00 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (157, 'Forgotten Summers: The Story of the Citizens\' Military Training Camps, 1921-1940', 149, 75, 76, 'US$39.00 ', 1995);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (158, 'The Life of John Marshall: Four Volumes in Two Books', 150, 75, 76, 'US$19.00 ', 1916);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (159, 'Challenges (Signed First Edition)', 151, 76, 77, 'US$650.00 ', 1967);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (160, 'Collected Poems (Signed First Edition)', 152, 76, 77, 'US$350.00 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (161, 'Your Hidden Skills: Clues to Careers and Future Pursuits', 153, 77, 78, 'US$22.00 ', 1981);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (162, 'Sturtevant Heating and Ventilation', 154, 77, 78, 'US$24.00 ', 1914);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (163, 'Prescriptions for Living: Inspirational Lessons for a Joyful, Loving Life', 155, 77, 78, 'US$18.00 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (164, 'In Search of South Africa', 156, 78, 79, 'US$60.00 ', 1948);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (165, 'Sandy Tracks to the Kraal', 157, 78, 79, 'US$70.00 ', 1956);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (166, 'Richardsrun: Cape Agulhas to Kilimanjaro on foot', 158, 78, 79, 'US$35.00 ', 2012);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (167, 'Do not take this road to El-Karama', 159, 78, 79, 'US$8.00 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (168, 'Hope in Thyme: A Journey along the Coast of South Africa', 160, 78, 79, 'US$14.00 ', 2009);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (169, 'THE ART OF FARRIERY both in theory and practice', 161, 79, 43, 'US$67.50 ', 1759);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (170, 'The Dragon Waiting: A Masque of History', 162, 79, 43, 'US$61.00 ', 1983);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (171, 'Under Taos Mountain: The Terrible Quarrel Of Magpie And Tia', 163, 79, 43, 'US$9.50 ', 2009);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (172, 'The Words of My Perfect Teacher, Revised Edition (Sacred Literature Series)', 164, 79, 43, 'US$77.50 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (173, 'The Element Encyclopedia of Witchcraft: The Complete A-Z for the Entire Magical World', 165, 79, 43, 'US$41.00 ', 2005);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (174, 'Best of the Hammer, Vol. 1', 166, 79, 43, 'US$77.50 ', 1985);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (175, 'The Conservative Complete, 1915 - 1923 -by H P Lovecraft / Necronomicon Press', 167, 80, 80, 'US$21.21 ', 1977);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (176, 'Rivers', 168, 81, 81, 'US$32.69 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (177, 'The Magpies: The Ecology and Behaviour of Black-billed and Yellow-billed Magpies', 169, 81, 81, 'US$32.69 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (178, 'The Golden Eagle (T & AD Poyser)', 170, 81, 81, 'US$19.61 ', 1997);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (179, 'Birds of Kenya and Northern Tanzania', 171, 81, 81, 'US$22.89 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (180, 'Extinct Birds', 172, 81, 81, 'US$21.58 ', 2012);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (181, 'Jesus Out to Sea; and Other Stories', 173, 82, 54, 'US$91.30 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (182, 'Ali\'s Smile / Naked Scientology', 174, 82, 54, 'US$60.50 ', 1978);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (183, 'The Bear and the Bird King', 175, 83, 82, 'US$25.00 ', 1994);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (184, 'Grandfather\'s Journey', 176, 83, 82, 'US$10.00 ', 1993);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (185, 'Once a Mouse.', 177, 83, 82, 'US$4.50 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (186, 'Brundibar', 178, 83, 82, 'US$5.00 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (187, 'Dreaming of You', 179, 84, 4, 'US$5.00 ', 1994);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (188, 'Cinders to Satin', 180, 84, 4, 'US$5.00 ', 1990);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (189, 'Wolf and the Dove', 181, 84, 4, 'US$5.00 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (190, 'Wheres My Hero?', 182, 84, 4, 'US$5.00 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (191, 'Antarctica: A Year at the Bottom of the World', 183, 85, 83, 'US$20.00 ', 2002);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (192, 'French Lessons in Africa: Travels With My Briefcase Through French Africa', 184, 85, 83, 'US$7.06 ', 1994);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (193, 'A Year in Provence', 185, 85, 83, 'US$9.41 ', 1991);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (194, 'Smert i deva. Ekho neznakomtsev', 186, 32, 84, 'US$9.04 ', 2019);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (195, 'Murder on the Leviathan. Erast Fandorin 3', 187, 32, 84, 'US$9.94 ', 2004);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (196, 'Chasovschik s Filigrannoj ulitsy', 188, 32, 84, 'US$14.46 ', 2019);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (197, 'Tokijskij Zodiak', 189, 32, 84, 'US$18.08 ', 2023);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (198, 'Verekuu', 190, 32, 84, 'US$9.04 ', 2023);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (199, 'The Myth of Freedom and the Way of Meditation (Shambhala Classics)', 191, 86, 85, 'US$3.00 ', 2002);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (200, 'Destructive Emotions: How Can We Overcome Them? A Scientific Dialogue with the Dalai Lama', 192, 86, 85, 'US$10.00 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (201, 'The Vision of the Buddha', 193, 86, 85, 'US$15.00 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (202, 'Mind-Seal of the Buddhas: Patriarch Ou-i\'s Commentary on the Amitabha Sutra', 194, 86, 85, 'US$30.00 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (203, 'Dharma Moments', 195, 86, 85, 'US$7.50 ', 2005);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (204, 'Tree of Life: Buddhism and Protection of Nature', 196, 86, 85, 'US$6.50 ', 1987);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (205, 'The history of Goody Two-Shoes', 197, 87, 86, 'US$45.77 ', 1830);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (206, 'The two dolls', 198, 87, 86, 'US$45.77 ', 1826);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (207, 'The merry tales of the wise men of Gotham.', 199, 87, 86, 'US$104.61 ', 1785);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (208, 'Watts\' divine songs in easy language for the use of children', 199, 87, 86, 'US$111.15 ', 1810);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (209, 'The adventures of Captain Gulliver', 200, 87, 86, 'US$44.46 ', 1810);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (210, 'The warbler of the woods; a collection of choice songs.', 200, 87, 86, 'US$49.69 ', 1830);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (211, 'The history of Whittington and his cat, and the story of Puss in boots. 161 [ Dick Whittington ]', 197, 87, 86, 'US$104.61 ', 1850);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (212, 'Everybody\'s Fool: A novel', 201, 88, 87, 'US$50.00 ', 2016);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (213, 'The Heaven & Earth Grocery Store: A Novel', 202, 88, 87, 'US$35.00 ', 2023);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (214, 'Backcloth. The Final Volume of His Autobiography', 203, 89, 65, 'US$26.36 ', 1986);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (215, 'The Silkworm. A Cormoran Strike Novel', 204, 89, 65, 'US$32.96 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (216, 'The House of Doctor Dee', 205, 89, 65, 'US$47.07 ', 1993);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (217, 'Encyclopedia of World Military Aircraft - Single Volume Edition', 206, 90, 88, 'US$20.86 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (218, 'Vorlesungen zur Geschichtstheorie 1 (Signed)', 207, 90, 88, 'US$20.86 ', 1974);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (219, 'Ernst Kaltenbrunner: Ideological Soldier of the Third Reich', 208, 90, 88, 'US$48.32 ', 1984);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (220, 'Russia and Germany: A Century of Conflict (1965)', 209, 90, 88, 'US$28.70 ', 1965);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (221, 'Starry Messenger: A Book Depicting the Life of a Famous Scientist, Mathematician, Astronomer, Phi...', 210, 91, 89, 'US$12.00 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (222, 'Old Possum\'s Book of Practical Cats.', 211, 92, 90, 'US$125.00 ', 1982);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (223, 'Time of the Hero.', 212, 92, 90, 'US$250.00 ', 1966);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (224, 'The Unconsoled.', 213, 92, 90, 'US$150.00 ', 1995);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (225, 'Song of Solomon.', 214, 92, 90, 'US$100.00 ', 1995);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (226, 'Unattainable Earth.', 215, 92, 90, 'US$25.00 ', 1986);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (227, 'Collected Poems, 1948-1984.', 216, 92, 90, 'US$45.00 ', 1992);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (228, 'Usagi Yojimbo Volume 23: Bridge of Tears', 217, 93, 91, 'US$12.50 ', 2009);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (229, 'The Ghost in the Shell Vol. 1 (Koukaku Kidoutai) (in Japanese)', 218, 93, 91, 'US$19.95 ', 1991);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (230, 'Vampire Knight, Vol. 19 (19)', 219, 93, 91, 'US$45.00 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (231, 'Alien Nine: Emulators', 220, 93, 91, 'US$29.95 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (232, 'K-ON!, Vol. 4', 221, 93, 91, 'US$14.95 ', 2011);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (233, 'GTO: Great Teacher Onizuka, Vol. 4', 222, 93, 91, 'US$24.00 ', 2002);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (234, 'The Hobbit, or There and back again', 223, 94, 92, 'US$124.22 ', 1968);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (235, 'East of the Sun and West of the Moon', 224, 94, 92, 'US$65.38 ', 1983);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (236, 'Mr Poppleberry and Fred the White Cockatoo', 225, 94, 92, 'US$45.77 ', 1990);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (237, 'Orlando the Marmalade Cat Keeps a Dog', 226, 94, 92, 'US$948.02 ', 1975);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (238, 'Are all the Giants Dead?', 224, 94, 92, 'US$39.23 ', 1983);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (239, 'Tomb Raider Volume 1 : Season of the Witch', 132, 71, 93, 'US$4.99 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (240, 'ApocalyptiGirl: An Aria for the End Times', 227, 71, 93, 'US$7.50 ', 2015);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (241, 'Star Wars: Jango Fett', 228, 71, 93, 'US$49.99 ', 2002);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (242, 'R.I.P.D. Volume 2: City of the Damned', 229, 71, 93, 'US$12.95 ', 2013);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (243, 'Apocalypse Suite 1 The Umbrella Academy', 230, 71, 93, 'US$19.99 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (244, 'Dallas 2 The Umbrella Academy', 231, 71, 93, 'US$8.99 ', 2009);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (245, 'HANG-UPS paintings by jonathan winters', 232, 95, 94, 'US$57.94 ', 1988);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (246, 'California Hot Shoes, CRA Sprint Cars 1955-1970, Volume 1', 233, 95, 94, 'US$30.00 ', 1978);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (247, 'Merrick - 1st Edition/1st Printing', 234, 96, 95, 'US$60.33 ', 2000);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (248, 'Violin - 1st Trade Edition', 234, 96, 95, 'US$371.25 ', 1997);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (249, 'Blood and Gold - 1st Edition/1st Printing', 235, 96, 95, 'US$40.00 ', 2001);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (250, 'Servant of the Bones - Limited B.E. Trice Edition', 234, 96, 95, 'US$51.05 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (251, 'The Best Of Me - 1st Edition/1st Printing', 236, 97, 96, 'US$156.62 ', 2011);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (252, 'The Wedding', 236, 97, 96, 'US$25.00 ', 2003);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (253, 'Message in a Bottle - 1st Edition/1st Printing', 237, 97, 96, 'US$79.95 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (254, 'At First Sight - 1st Edition/1st Printing', 236, 97, 96, 'US$25.00 ', 2005);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (255, 'A Bend in the Road', 236, 97, 96, 'US$40.43 ', 2001);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (256, 'HOUSE OF LEAVES', 238, 98, 97, 'US$1,250.00 ', 2000);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (257, 'PET SEMATARY (signed 1st)', 239, 98, 97, 'US$27.00 ', 1983);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (258, 'THE STAND (SIGNED AND INSCRIBED)', 240, 98, 97, 'US$39.00 ', 1978);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (259, 'Prince Lestat: The Vampire Chronicles', 241, 98, 97, 'US$1,495.00 ', 2014);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (260, 'Spook Country', 241, 98, 97, 'US$79.12 ', 2007);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (261, 'The Killing Kind', 242, 98, 97, 'US$25.00 ', 2001);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (262, 'Drums of Autumn', 243, 99, 4, 'US$25.00 ', 1997);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (263, 'PASSION\'S PRIZE', 245, 99, 4, 'US$1.00 ', 1990);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (264, 'Shlomo Zabludowicz. Holokaustin kauhuista salaperäiseksi suomalaismiljardööriksi', 246, 99, 4, 'US$4.75 ', 2021);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (265, 'Natsit tiesivät nimeni. Tarina selviytymisestä ja rohkeudesta Auschwitzissa', 4, 99, 4, 'US$1.35 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (266, 'Lupauksen voima. Kuinka selviydyin Auschwitzista ja säilytin elämänhaluni', 247, 99, 4, 'US$4.20 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (267, 'The Cat in the Hat', 248, 100, 98, 'US$491.11 ', 1958);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (268, 'Bewilderment', 249, 100, 98, 'US$55.00 ', 1974);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (269, 'The Art of Michael Whelan', 250, 100, 98, 'US$68.00 ', 2001);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (270, 'Twenty Poems', 251, 100, 98, 'US$1,850.00 ', 1988);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (271, 'The Information: A History, A Theory, A Flood', 252, 100, 98, 'US$295.00 ', 2002);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (272, 'BIRDS. The Paintings of Terance James Bond. Signed Limited Edition', 253, 100, 98, 'US$950.00 ', 2021);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (273, 'MURDER BY OWL LIGHT', 254, 101, 99, 'US$27.26 ', 1992);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (274, 'TWO FOR THE LIONS', 255, 101, 99, 'US$8.18 ', 1998);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (275, '13 FOR LUCK! : A Selection of Mystery Stories', 256, 101, 99, 'US$6.82 ', 1966);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (276, 'Drawing Conclusions', 256, 101, 99, 'US$6.82 ', 2011);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (277, 'Nemesis', 256, 101, 99, 'US$6.82 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (278, 'Coffin Road', 254, 101, 99, 'US$51.12 ', 2016);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (279, 'The Lord of the Rings. The Fellowship of the Ring; The Two Towers; The Return of the King', 223, 102, 100, 'US$135,000.00 ', 1954);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (280, 'American Dirt: A Novel ***AUTHOR SIGNED***', 257, 102, 100, 'US$150.00 ', 2020);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (281, 'Rosa Parks: My Story', 258, 102, 100, 'US$81.47 ', 1992);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (282, 'The Invention of Hugo Cabret', 259, 102, 100, 'US$40.00 ', 2007);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (283, 'The Maidens: A Novel *** AUTHOR SIGNED ARC', 260, 102, 100, 'US$45.00 ', 2021);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (284, 'The Fault in Our Stars', 261, 102, 100, 'US$79.35 ', 2012);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (285, 'March: A Novel ***AUTHOR SIGNED***', 262, 102, 100, 'US$65.00 ', 2005);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (286, 'Cloud Cuckoo Land', 263, 103, 101, 'US$76.00 ', 2021);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (287, 'Our Missing Hearts', 264, 103, 101, 'US$61.00 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (288, 'The Candy House', 265, 103, 101, 'US$62.00 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (289, 'Audition: A Memoir', 266, 103, 101, 'US$49.00 ', 2008);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (290, 'Go Tell the Bees That I Am Gone', 267, 103, 101, 'US$59.00 ', 2021);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (291, 'The Water Dancer', 268, 103, 101, 'US$64.00 ', 2019);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (292, 'The Wager: A Tale of Shipwreck, Mutiny and Murder', 269, 104, 65, 'US$150.00 ', 2023);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (293, 'A Gentleman in Moscow: A Novel', 269, 104, 65, 'US$65.00 ', 2016);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (294, 'Circe', 270, 104, 65, 'US$125.00 ', 2018);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (295, 'What Do You Care What Other People Think?: Further Adventures of a Curious Character', 271, 104, 65, 'US$65.00 ', 1988);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (296, 'The Song of the Cell: An Exploration of Medicine and the New Human', 249, 104, 65, 'US$85.00 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (297, 'Freewater (Newbery & Coretta Scott King Award Winner)', 272, 104, 65, 'US$55.00 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (298, 'Night of the Living Rez', 273, 104, 65, 'US$75.00 ', 2022);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (299, 'The Art of Engraving', 274, 105, 102, 'US$32.69 ', 1973);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (300, 'Tom Tichenor\'s Puppets', 275, 105, 102, 'US$20.00 ', 1971);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (301, 'Prihynur og langsjöl - Icelandic edition, signed', 276, 105, 102, 'US$150.00 ', 1988);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (302, 'The Art of Fair Isle: History, Technique, Color & Patterns', 277, 105, 102, 'US$84.99 ', 1996);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (303, 'From Felt to Fabric: New Techniques in Nuno Felting (Signed)', 278, 105, 102, 'US$32.69 ', 2011);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (304, 'Flip! for Decorating: A Page-by-Page, Piece-by-Piece, Room-by-Room Guide to Transforming Your Home', 279, 105, 102, 'US$20.00 ', 2009);
INSERT INTO bookstoredb.books (book_id, bname, author_id, pub_id, category_id, price, pub_year) VALUES (305, 'CALENDAR CLOCKS (with 1993 & 2000 Price Updates)', 280, 105, 102, 'US$95.00 ', 1993);
