create table category
(
    category_id   int          not null
        primary key,
    category_name varchar(255) not null
);

INSERT INTO bookstoredb.category (category_id, category_name) VALUES (0, 'Bible Study');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (1, 'Dreams');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (2, 'Time Management');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (3, 'Astronomy');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (4, 'Historical Romance');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (5, 'Antiques');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (6, 'Dr Seuss Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (7, 'Cookbooks General');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (8, 'Hypnosis');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (9, 'Travel, Asia');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (10, 'Fantasy');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (11, 'Gardening');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (12, 'Travel, Iconic');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (13, 'Christian Bible Study');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (14, 'Manga');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (15, 'Signed, Association Copies');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (16, 'Luggage Labels');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (17, 'Bibliography');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (18, 'American Literature');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (19, 'Architecture');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (20, 'Accounting');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (21, 'Fine Bindings');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (22, 'Horror & Ghost Stories');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (23, 'Signed and Inscribed Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (24, 'New Age');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (25, 'Local History (Directories)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (26, 'Cookbooks');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (27, 'Biology');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (28, 'Dictionaries');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (29, 'Agatha Christie');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (30, 'Travel, Africa');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (31, 'Travel (Asia)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (32, 'Memoirs');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (33, 'European History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (34, 'Ghost Stories');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (35, 'Music Performing Art Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (36, 'Hinduism');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (37, 'Bibliography, Book Arts, Fine Printing');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (38, 'Food Writing');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (39, 'Crime Fiction');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (40, 'Atlases');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (41, 'Art History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (42, 'Politics');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (43, 'Ancient History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (44, 'Business, Management And Corporate');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (45, 'Graphic Novels Youth');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (46, 'Fantasy Fiction Hardcovers');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (47, 'Business and Industry');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (48, 'Music (Biographies)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (49, 'Textiles');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (50, 'Fine Press');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (51, 'Caldecott Medal Winners');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (52, 'Autographs & Manuscripts');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (53, 'Agriculture');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (54, 'Literary First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (55, 'Music (Vintage Sheet Music 1900-1909)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (56, 'Children-Board Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (57, 'Humanities');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (58, 'Biographies of Horses and People');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (59, 'Science Fiction');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (60, 'American History (Presidents)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (61, 'Broadsides & Prints');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (62, 'Vintage Magazines');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (63, 'Book Arts');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (64, 'Journals, Periodicals and Magazines');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (65, 'Modern First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (66, 'Signed Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (67, 'Personal Memoirs');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (68, 'Rivers');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (69, 'Latin American Literature');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (70, 'DC Comics');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (71, 'Photographs');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (72, 'Antiquarian');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (73, 'Poetry');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (74, 'Canadian Vintage PB Harlequin Collins White Circle');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (75, 'Diet');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (76, 'American History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (77, 'Association Copies');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (78, 'Self Help Hypnosis How To');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (79, 'Travel (Africa)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (80, 'H P Lovecraft');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (81, 'Art Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (82, 'Children\'s Illustrated');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (83, 'Travel, Travel Writing, Travel Adventure');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (84, 'Detective');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (85, 'Buddhism');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (86, 'Chapbooks and broadsides');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (87, 'Signed & Inscribed');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (88, 'Politics & Government');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (89, 'Children\'s Picture Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (90, 'Nobel Prize Winners');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (91, 'Manga Box');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (92, 'Children\'s Illustrated Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (93, 'Dark Horse');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (94, 'Crafts And Hobbies');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (95, 'Fiction (Horror)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (96, 'Fiction (Romance)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (97, 'Horror');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (98, 'Signed First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (99, 'Fiction (Crime Fiction)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (100, 'Signed');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (101, 'First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (102, 'Crafts & Hobbies');
