create table category
(
    category_id   int          not null
        primary key,
    category_name varchar(255) not null
);

INSERT INTO bookstoredb.category (category_id, category_name) VALUES (0, 'Bible Study');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (1, 'New Age');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (2, 'Adventure Fiction');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (3, 'Travel & Adventure (Travel)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (4, 'Dreams');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (5, 'Fairy Tales, Mythology, & Folklore');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (6, 'Food Writing');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (7, 'Astronomy');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (8, 'Biology');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (9, 'Hypnosis');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (10, 'Cookbooks General');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (11, 'Cookbooks');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (12, 'Dreams, dreaming, dream');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (13, 'Travel (Asia)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (14, 'Christian Bible Study');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (15, 'Gardening');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (16, 'Graphic Novels');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (17, 'Business');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (18, 'Sketches, Cartoons, & Caricatures');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (19, 'Manga');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (20, 'Board Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (21, 'Reference Dictionaries');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (22, 'Science Fiction');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (23, 'Accounting');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (24, 'Architecture');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (25, 'Children\'s Picture Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (26, 'Metaphysics');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (27, 'Agatha Christie');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (28, 'Hinduism');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (29, 'Agriculture');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (30, 'Fiction (Adventure Fiction)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (31, 'Art History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (32, 'Caldecott Medal Winners');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (33, 'Politics');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (34, 'Ancient History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (35, 'Music Performing Art Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (36, 'Humanities');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (37, 'Business and Industry');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (38, 'Music (Biographies)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (39, 'Fantasy Fiction Hardcovers');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (40, 'Graphic Novels Youth');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (41, 'Manga Box');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (42, 'DC Comics');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (43, 'Children\'s Illustrated Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (44, 'Literary First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (45, 'Children-Board Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (46, 'American History (Presidents)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (47, 'Dark Horse');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (48, 'American History');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (49, 'Modern First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (50, 'Detective');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (51, 'H P Lovecraft');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (52, 'Art Books');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (53, 'Personal Memoirs');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (54, 'Diet');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (55, 'Historical Romance');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (56, 'Association Copies');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (57, 'Children\'s Illustrated');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (58, 'Latin American Literature');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (59, 'Travel (Africa)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (60, 'Nobel Prize Winners');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (61, 'Buddhism');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (62, 'Signed & Inscribed');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (63, 'Self Help Hypnosis How To');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (64, 'Travel, Travel Writing, Travel Adventure');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (65, 'Crafts And Hobbies');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (66, 'Fiction (Horror)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (67, 'Fiction (Romance)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (68, 'Fiction (Crime Fiction)');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (69, 'Crafts & Hobbies');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (70, 'Horror');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (71, 'Signed');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (72, 'First Editions');
INSERT INTO bookstoredb.category (category_id, category_name) VALUES (73, 'Signed First Editions');
