create table publishers
(
    pub_id int          not null
        primary key,
    pname  varchar(255) not null
);

INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (0, 'Old Favorites Bookshop LTD (since 1954)');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (1, 'Streamside Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (2, 'Biblio Pursuit');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (3, 'Bookmarc\'s');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (4, 'Kona Bay Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (5, 'Underground Books, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (6, 'Book House in Dinkytown, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (7, 'Lady Lisa\'s Bookshop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (8, 'Metakomet Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (9, 'Rob the Book Man');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (10, 'Copperfield\'s Used and Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (11, 'Book Grove, RMABA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (12, 'Bolerium Books Inc.');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (13, 'Hall of Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (14, 'The Old Bookshelf');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (15, 'Oakholm Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (16, 'Brentwood Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (17, 'Before Your Quiet Eyes');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (18, 'Borg Antiquarian');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (19, 'James F. Balsley, Bookseller');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (20, 'Granny Goose Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (21, 'M.Roberts - Books And ??????');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (22, 'a2zbooks');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (23, 'Balfour Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (24, 'Champ & Mabel Collectibles');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (25, 'Pistil Books Online, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (26, 'Caspian Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (27, 'Paperworks');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (28, 'Lake Country Books and More');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (29, 'Vedic Book Services');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (30, 'Granada Bookstore,            IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (31, 'Colin Martin Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (32, 'Soaring Hawk Vintage');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (33, 'Portman Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (34, 'Banfield House Booksellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (35, 'Ruslania');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (36, 'Robinson Street Books, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (37, 'Paraphernalia Books \'N\' Stuff');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (38, 'Dunaway Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (39, 'Kirk Ruebotham Bookseller');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (40, 'Inquiring Minds');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (41, 'Recycle Bookstore');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (42, 'Firefly Bookstore');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (43, 'MacKellar Art &  Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (44, 'Tennyson Williams Books and Fine Art');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (45, 'Strand Book Store, ABAA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (46, 'Arroway Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (47, 'Crooked House Books & Paper, CBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (48, 'The Book House, Inc.  - St. Louis');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (49, 'Bingo Books 2');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (50, 'Anthology Booksellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (51, 'Mainly Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (52, 'The London Bookworm');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (53, 'Leonard Shoup');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (54, 'St Paul\'s Bookshop P.B.F.A.');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (55, 'Great Southern Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (56, '100POCKETS');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (57, 'Read It Again Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (58, 'Dan Pope Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (59, 'Books End Bookshop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (60, 'Abacus Bookshop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (61, 'Chapter 1');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (62, 'Grendel Books, ABAA/ILAB');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (63, 'Molly\'s Brook Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (64, 'About Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (65, 'Vandello Books, Member IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (66, 'Gene The Book Peddler');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (67, 'The Parnassus BookShop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (68, '27 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (69, '22 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (70, '25 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (71, '109 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (72, '13 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (73, '2 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (74, '82 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (75, '272 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (76, '218 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (77, '150 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (78, '45 sellers');
