create table publishers
(
    pub_id int          not null
        primary key,
    pname  varchar(255) not null
);

INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (0, 'Old Favorites Bookshop LTD (since 1954)');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (1, 'Kona Bay Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (2, 'ThatsTheCatsMeow');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (3, 'Sparrow\'s Bookshop, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (4, 'Never Too Many Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (5, 'Goldring Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (6, 'Linda\'s Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (7, 'Copperfield\'s Used and Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (8, 'Rob the Book Man');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (9, 'Sapience Bookstore');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (10, 'Librarium');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (11, 'Oakholm Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (12, 'Ashton Rare Books  ABA : PBFA : ILAB');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (13, 'The Old Bookshelf');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (14, 'James F. Balsley, Bookseller');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (15, 'Zetetic Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (16, 'Picture This (ABA, ILAB, IVPDA)');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (17, 'Leakey\'s Bookshop Ltd.');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (18, 'Charles Lewis Best Booksellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (19, 'Balfour Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (20, 'a2zbooks');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (21, 'Candleleaf');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (22, 'The Book Nest Ltd');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (23, 'Thompson Rare Books - ABAC / ILAB');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (24, 'Mare Booksellers ABAA, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (25, 'CHILTON BOOKS');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (26, 'Book Grove, RMABA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (27, 'Lake Country Books and More');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (28, 'Regent College Bookstore');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (29, 'Paperworks');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (30, 'Hall of Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (31, 'Horizon Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (32, 'Ruslania');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (33, 'Vedic Book Services');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (34, 'J & J House Booksellers, ABAA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (35, 'cookbookjj');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (36, '95 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (37, 'Rooke Books PBFA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (38, 'Open Door Books  MABA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (39, 'Portman Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (40, 'Banfield House Booksellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (41, 'Neville Wade');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (42, 'Inquiring Minds');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (43, 'Kirk Ruebotham Bookseller');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (44, 'Paraphernalia Books \'N\' Stuff');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (45, 'Dunaway Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (46, 'Pistil Books Online, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (47, 'Carpe Diem Fine Books, ABAA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (48, 'Soaring Hawk Vintage');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (49, 'Zamboni & Huntington');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (50, 'Granada Bookstore,            IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (51, 'Brought to Book Ltd');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (52, 'The Groaning Board');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (53, 'Tennyson Williams Books and Fine Art');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (54, '! Turtle Creek Books  !');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (55, 'Strand Book Store, ABAA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (56, 'Robinson Street Books, IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (57, 'Robin Bledsoe, Bookseller (ABAA)');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (58, 'High Ridge Books, Inc. - ABAA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (59, 'World of Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (60, 'Arroway Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (61, 'The Book House, Inc.  - St. Louis');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (62, 'F枚ldv谩ri Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (63, 'Arundel Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (64, '32.1  Rare Books + Ephemera, IOBA, ESA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (65, 'Wittenborn Art Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (66, 'About Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (67, 'Whitmore Rare Books, Inc. -- ABAA, ILAB');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (68, 'Great Southern Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (69, 'Attic Books (ABAC, ILAB)');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (70, 'Abacus Bookshop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (71, 'Firefly Bookstore');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (72, 'Carmarthenshire Rare Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (73, 'Comic World');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (74, '100POCKETS');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (75, 'Mainly Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (76, 'Dan Pope Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (77, 'Gene The Book Peddler');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (78, 'Chapter 1');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (79, 'Bingo Books 2');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (80, 'Leonard Shoup');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (81, 'St Paul\'s Bookshop P.B.F.A.');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (82, 'Anthology Booksellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (83, 'Books End Bookshop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (84, 'Read It Again Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (85, 'The Parnassus BookShop');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (86, 'Molly\'s Brook Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (87, 'Stephen Rench');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (88, 'Vandello Books, Member IOBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (89, 'The London Bookworm');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (90, 'Maynard & Bradley');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (91, 'Crooked House Books & Paper, CBA');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (92, 'Grendel Books, ABAA/ILAB');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (93, 'Recycle Bookstore');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (94, 'MacKellar Art &  Books');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (95, '27 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (96, '22 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (97, '25 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (98, '272 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (99, '13 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (100, '45 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (101, '2 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (102, '218 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (103, '150 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (104, '109 sellers');
INSERT INTO bookstoredb.publishers (pub_id, pname) VALUES (105, '82 sellers');
