# Generated by Django 4.2.1 on 2023-12-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('pub_year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.users')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.users')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.users')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='publishers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookStore.publishers'),
        ),
        migrations.AddConstraint(
            model_name='shoppinghistory',
            constraint=models.UniqueConstraint(fields=('uid', 'book'), name='shoppingHistory'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcarts',
            constraint=models.UniqueConstraint(fields=('uid', 'book'), name='shoppingCarts'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcarts',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='amount__gt=0'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('uid', 'book'), name='collection'),
        ),
    ]
