# Generated by Django 4.2.1 on 2023-12-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcarts',
            name='shoppingCarts',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinghistory',
            name='shoppingHistory',
        ),
        migrations.RemoveField(
            model_name='users',
            name='passwd',
        ),
        migrations.AddField(
            model_name='users',
            name='pwdhash',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shoppingcarts',
            constraint=models.UniqueConstraint(fields=('uid', 'book'), name='shoppingcarts'),
        ),
        migrations.AddConstraint(
            model_name='shoppinghistory',
            constraint=models.UniqueConstraint(fields=('uid', 'book'), name='shoppinghistory'),
        ),
    ]
