# Generated by Django 4.2.1 on 2023-12-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='book',
            field=models.ForeignKey(db_column='book_id', help_text='书的序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.books'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(db_column='uid', help_text='用户序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.users'),
        ),
        migrations.AlterField(
            model_name='shoppingcarts',
            name='book',
            field=models.ForeignKey(db_column='book_id', help_text='书的序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.books'),
        ),
        migrations.AlterField(
            model_name='shoppingcarts',
            name='user',
            field=models.ForeignKey(db_column='uid', help_text='用户序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.users'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='book',
            field=models.ForeignKey(db_column='book_id', help_text='书的序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.books'),
        ),
        migrations.AlterField(
            model_name='shoppinghistory',
            name='user',
            field=models.ForeignKey(db_column='uid', help_text='用户序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.users'),
        ),
    ]
