# Generated by Django 4.2.1 on 2023-12-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0002_alter_collection_book_alter_collection_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ForeignKey(db_column='author_id', help_text='作者序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(db_column='category_id', help_text='种类序号', on_delete=django.db.models.deletion.CASCADE, to='bookStore.category'),
        ),
    ]
