# Generated by Django 4.2.1 on 2023-12-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0003_alter_books_authors_alter_books_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppinghistory',
            table='shoppinghistory',
        ),
    ]
