# Generated by Django 4.2.1 on 2023-12-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0004_alter_shoppinghistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='bookStore.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bname',
            field=models.CharField(help_text='书名', max_length=255),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='bookStore.category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pub_year',
            field=models.IntegerField(help_text='出版年份'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishers',
            field=models.ForeignKey(db_column='pub_id', on_delete=django.db.models.deletion.CASCADE, to='bookStore.publishers'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(help_text='用户邮箱', max_length=100, null=True),
        ),
    ]
