# Generated by Django 4.2.1 on 2023-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0005_alter_books_authors_alter_books_bname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='publishers',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, help_text='用户邮箱', max_length=100, null=True),
        ),
    ]
