# Generated by Django 4.2.1 on 2023-12-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookStore', '0001_squashed_0005_alter_books_publishers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authors',
        ),
    ]
